name: flashlight_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Architecture & State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # Network & Data
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0

  # UI (Optional but good for modern UI)
  google_fonts: ^6.2.1
  freezed_annotation: ^3.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  freezed: ^3.2.3

flutter:
  uses-material-design: true
